---
name: Docker Build Action
on:
  push:

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/metal-stack/dns-controller-manager:powerdns
